### ISSUE TITLE
Multiplayer with this mod causes black screen

### ISSUE THREAD

**Issue by takanas** [netux/BeatSaber-BeatmapPlayCount#1]
At least when using beattogether my game freezes/blacks screens after starting a level. Removing this mod fixes it so pretty sure its causing it or conflicting with some other mod.

**Comment by netux** [comment]
@takanas thanks for reaching out. Could you provide the following information?
- Platform (PC or Quest)
- Beat Saber version
- Mod version

**Comment by takanas** [comment]
Im playing on pc on 1.24.1 beat saber version and tried both 0.1.0 and 0.2.0 versions

**Comment by netux** [comment]
Just published [release v0.2.1](https://github.com/netux/BeatSaber-BeatmapPlayCount/releases/tag/v0.2.1) with a fix. Let me know if that solved the crash.

Note that the fix is just avoiding running some logic in multiplayer. Play count won't be increased for songs played during multiplayer yet.

**Comment by netux** [comment]
Heya @takanas. Just checking: was the issue resolved?

**Comment by takanas** [comment]
Oh yeah sorry forgot to respond but it seems to work fine now. At least it allows me to start levels without blackscreening instantly

**Comment by netux** [comment]
Perfect. I will close this issue then.
