### ISSUE TITLE
Issue breaking Tutorial

### ISSUE THREAD

**Issue by Melopod** [netux/BeatSaber-BeatmapPlayCount#2]
Hi! We (BSMG Support) received a report from someone who had an issue with Counters+ locking their sabers.
It turns out this mod (BeatmapPlayCount) is breaking elements of the in-game tutorial on the current version of the game, causing Counters+ to break in turn. A snippet of the log here:
[CRITICAL @ 18:59:43 | UnityEngine] ZenjectException: Unable to resolve 'IDifficultyBeatmap' while building object with type 'TrackPlaytime'. Object graph:
[CRITICAL @ 18:59:43 | UnityEngine] SceneKernel
[CRITICAL @ 18:59:43 | UnityEngine] TickableManager
[CRITICAL @ 18:59:43 | UnityEngine] TrackPlaytime 
Game version: 1.25.1
Platform: Steam
As I am not the person with the issue itself I don't have any further info but I wanted to forward it. 
Thanks!

**Comment by Auros** [comment]
You can change the `Location.Singleplayer` [here](https://github.com/netux/BeatSaber-BeatmapPlayCount/blob/f48b93973628a414e4e24925049de88e93f04b63/BeatmapPlayCount/Plugin.cs#L33) to `Location.StandardPlayer  | Location.CampaignPlayer` to fix it.

**Comment by netux** [comment]
Thanks. I just published [release v0.2.2](https://github.com/netux/BeatSaber-BeatmapPlayCount/releases/tag/v0.2.2)  with the suggested fix.
